# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

students = Student.create([{name: 'joshua pann', email: 'josh.pann@gmail.com', github_username: 'jmpann', blog_url: ''},
{name: 'Andrew Nease', email: 'andrew.nease.code@gmail.com', github_username: 'andigan', blog_url: 'https://andigan.github.io'},
{name: 'Jing Yu', email: 'jingyu1@gmail.com', github_username: 'deaundrapeek', blog_url:'http://duncecapsforcats.com/'},
{name: 'Mohammed Chisti', email: 'mohammed.chisti@flatironschool.com', github_username: 'SeeYouSpaceCowboy', blog_url: 'https://medium.com/@mchisti' },
{name: 'Kavitoj Singh', email: 'kavitojsingh@gmail.com', github_username: 'KavitojSingh', blog_url:'https://medium.com/@kavitojsingh'},
{name: 'Yomi Lajide', email: 'alajide@gmail.com', github_username: 'Joll59', blog_url: 'https://medium.com/@alajide'},
{name:'Franco Cappitta', email: 'franco84@gmail.com', github_username: 'Franco84', blog_url: ''},
{name: 'Vic Lam', email: 'lam.vic.k@gmail.com', github_username: 'chplusink', blog_url: ''},
{name:'Jackson Hoang', email: 'jkhoang313@gmail.com', github_username: 'jkhoang313', blog_url: 'https://medium.com/@jkhoang313'},
{name:'Jason Decker', email: 'j@curiositypaths.com', github_username: 'curiositypaths', blog_url: 'https://medium.com/@curiositypaths'},
{name: 'Emily Croft', email: 'emilyhcroft@gmail.com', github_username: 'emilycroft', blog_url: 'https://medium.com/@emilyhcroft'},
{name: 'Christina Entcheva', email: 'christina.entcheva@gmail.com', github_username: 'entcheva', blog_url: 'entcheva.github.io'},
{name: 'David Weinstein', email: 'dwein9@gmail.com', github_username: 'Dwein9', blog_url:'https://medium.com/@txea/'},
{name:'Christi Reid', email: 'christi@limerentfox.com', github_username: 'limerentfox', blog_url: 'https://limerentfox.github.io/cultivating-awesome/'},
{name: 'David Korff', email: 'davidkorff@gmail.com', github_username: 'davidkorff', blog_url: 'https://medium.com/@davidkorff'},
{name: 'Kyle Tulod', email: 'https.www.user@gmail.com', github_username: 'Kighway', blog_url:'https://medium.com/@Kighway'},
{name: 'Jonathan Zylberberg', email: 'zylberberg.jonathan@gmail.com', github_username: 'ZylberbergJ23', blog_url: 'https://medium.com/@zylberberg.jonathan'},
{name: 'Kevin Wang', email: 'kev.wang424@gmail.com', github_username: 'kevwang424', blog_url: 'https://medium.com/@kev.wang424/'},
{name: 'Vinny Martinez', email: 'vinny@vinnymartinez.com', github_username: 'bobertoo', blog_url:'https://medium.com/@bobmeow'},
{name: 'Valerie McCarthy', email: 'valeriewilsonmccarthy@gmail.com', github_username: 'valeriemccarthy', blog_url:'https://medium.com/@valeriemccarthy'},
{name: 'Jenny Lai', email: 'jlai902@gmail.com', github_username: 'jenlaister', blog_url:'https://medium.com/@jennylaister/'},
{name: 'Joel Cowie', email: 'joel.a.cowie@gmail.com', github_username: 'joelcowie', blog_url: 'https://medium.com/@joel.cowie'},
{name: 'Jenny Kats', email: 'y.jennykats@gmail.com', github_username: 'jennykats', blog_url: 'https://medium.com/@jennykats'},
{name: 'Andrew Cohn', email: 'harrysancola@gmail.com', github_username: 'acohn93', blog_url: 'https://medium.com/@andrewcohn0', fun_fact: 'Horribly afraid of anything coming into contact with my eyelids'},
{name: 'Jennifer Wong', email: 'wongjenn@yahoo.com', github_username: 'wongjenn', blog_url: 'https://medium.com/@jenniferwong_94145/'},
{name: 'Eric Hasselbring', email: 'ehasselbring@gmail.com', github_username: 'hassey13', blog_url: 'https://medium.com/@ehassey13'},
{name: 'Frankie Ferreira', email: 'frankiemferreira@gmail.com', github_username: 'FrankieMFerreira', blog_url: 'https://medium.com/@frankie.ferreira'},
{name: 'Cathy Yee', email: 'catyyee@hotmail.com', github_username: 'cy2003', blog_url: 'https://medium.com/@cyee/loving-the-process-6a3b535b4af9#.krccjcgnf'},
{name: 'Joseph Sasson', email: 'ywebon88@gmail.com', github_username: 'joeweb', blog_url: 'https://joeweb.github.io/'},
{name: 'patty', email: 'patty.stacruz@gmail.com', github_username: 'pattysc', blog_url: 'https://pattyscoding.tumblr.com/'},
{name: 'Elizabeth Jacobs', email: 'elizabethjjacobs@gmail.com', github_username: 'lizzyjacobs', blog_url: 'https://medium.com/@elizabethjjacobs'},
{name: 'Ashley Robinson', email: 'ashleyhowerobinson@gmail.com', github_username: 'howers', blog_url: 'howers.github.io'},
{name: 'Rachel Salois', email: 'rachel.salois@gmail.com', github_username: 'RachelSa', blog_url: 'https://rachelscodenotes.wordpress.com'},
{name: 'Eric Schwartz', email: 'ericschwartz7@gmail.com', github_username: 'EricSchwartz7', blog_url: 'https://medium.com/@ericschwartz7'},
{name: 'Rob Hitt', email: 'robhitt@gmail.com', github_username: 'robhitt', blog_url:'https://medium.com/@robhitt'},
{name: 'Matt Fender', email: 'mjfender@gmail.com', github_username: 'mjfender', blog_url: 'https://medium.com/@mattfender/'},
{name: 'Clinton Nguyen', email: 'clinton.ngyn@gmail.com', github_username: 'clintonn', blog_url: 'http://blog.clinton.so/code/'},
{name: 'Adam Emrich', email: 'adam.emrich@gmail.com', github_username: 'aemrich', blog_url: 'medium.com/@adamenrich'}])

courses = Course.create([{title: 'web development', description:"Get a job as a full-stack web developer—guaranteed. In this Instructor-Led Bootcamp, you’ll take on our proven curriculum with the guidance of our best-in-class instructors and career coaches and the support of a dedicated student community. Our Job Guarantee means you can change careers with confidence."},
{title: 'ios development', description:"Learn how to make modern, advanced mobile applications. Understand important iOS topics like Objective-C, Swift, UIKit, and Core Data, along with soft skills like how to learn new languages and debug programs. Create real projects with actual developer tools like XCode, GitHub, and Bash. It’s hard work worth doing."},
{title: 'bootcamp prep', description: "Learn the programming fundamentals you’ll need to hit the ground running in today’s most selective coding bootcamps (and get a leg up when applying to ours!)."},
{title: 'intro to ruby', description:"Start coding with the language designed to make programmers happy. You’ll create an object-oriented Tic-Tac-Toe game while learning principles that will power your coding journey."},
{title: 'intro to javascript', description:"Harness the power of the modern web with the most popular language on the Internet. You’ll build a dynamic Konami code game while mastering the latest JavaScript syntax and techniques."},
{title: 'html & css', description: "Learn how to create responsive, pixel-perfect websites from scratch."},
{title: 'react', description: "Learn to create powerful front-end applications with Facebook’s new framework."}])

course_students = CourseStudent.create([
{student_id: 0, course_id: 1},
{student_id: 2, course_id: 1},
{student_id: 1, course_id: 1},
{student_id: 3, course_id: 1},
{student_id: 4, course_id: 1},
{student_id: 5, course_id: 1},
{student_id: 6, course_id: 1},
{student_id: 7, course_id: 1},
{student_id: 8, course_id: 1},
{student_id: 9, course_id: 1},
{student_id: 10, course_id: 1},
{student_id: 11, course_id: 1},
{student_id: 12, course_id: 1},
{student_id: 13, course_id: 1},
{student_id: 14, course_id: 1},
{student_id: 15, course_id: 1},
{student_id: 16, course_id: 1},
{student_id: 17, course_id: 1},
{student_id: 18, course_id: 1},
{student_id: 19, course_id: 1},
{student_id: 20, course_id: 1},
{student_id: 21, course_id: 1},
{student_id: 22, course_id: 1},
{student_id: 25, course_id: 1},
{student_id: 26, course_id: 1},
{student_id: 27, course_id: 1},
{student_id: 28, course_id: 1},
{student_id: 29, course_id: 1},
{student_id: 24, course_id: 1},
{student_id: 23, course_id: 1},
{student_id: 30, course_id: 1},
{student_id: 31, course_id: 1},
{student_id: 32, course_id: 1},
{student_id: 33, course_id: 1},
{student_id: 34, course_id: 1},
{student_id: 35, course_id: 1},
{student_id: 36, course_id: 1},
{student_id: 37, course_id: 1},
{student_id: 1, course_id: 0},
{student_id: 2, course_id: 0},
{student_id: 1, course_id: 0},
{student_id: 3, course_id: 0},
{student_id: 4, course_id: 0},
{student_id: 5, course_id: 0},
{student_id: 6, course_id: 0},
{student_id: 7, course_id: 0},
{student_id: 8, course_id: 0},
{student_id: 9, course_id: 10},
{student_id: 10, course_id: 2},
{student_id: 11, course_id: 2},
{student_id: 12, course_id: 2},
{student_id: 13, course_id: 2},
{student_id: 14, course_id: 2},
{student_id: 15, course_id: 2},
{student_id: 16, course_id: 2},
{student_id: 17, course_id: 2},
{student_id: 18, course_id: 2},
{student_id: 19, course_id: 2},
{student_id: 20, course_id: 3},
{student_id: 21, course_id: 3},
{student_id: 22, course_id: 3},
{student_id: 25, course_id: 3},
{student_id: 26, course_id: 3},
{student_id: 27, course_id: 3},
{student_id: 28, course_id: 3},
{student_id: 29, course_id: 3},
{student_id: 24, course_id: 3},
{student_id: 23, course_id: 3},
{student_id: 30, course_id: 4},
{student_id: 31, course_id: 4},
{student_id: 32, course_id: 4},
{student_id: 33, course_id: 4},
{student_id: 34, course_id: 4},
{student_id: 35, course_id: 4},
{student_id: 36, course_id: 4},
{student_id: 37, course_id: 4}
])
